spring.application.name=backend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://kabhins0612:12345@cluster.wvs9sbd.mongodb.net/orphanage?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://kabhins0612:12345@cluster.wvs9sbd.mongodb.net/orphanage?retryWrites=true&w=majority

jwt.secret=94a08da1fecbb6e8b46990538c7b50b28ec4b953a992a720042f3ea3b1158a13
jwt.expiration=36000000

# Reduce verbose MongoDB driver logging
logging.level.org.mongodb.driver=WARN
